[platformio]
default_envs = rover, base

[common]
platform = https://github.com/pioarduino/platform-espressif32.git
board = esp32-c6-devkitm-1
framework = arduino
board_build.partitions = min_spiffs.csv
monitor_speed = 115200
upload_speed = 921600
build_flags = 
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DARDUINO_USB_MODE=1
    -I include

[env:rover]
extends = common
build_src_filter = 
    +<rover/*>
    -<base/*>
build_flags = 
    ${common.build_flags}
    -DBUILD_ROVER=1
lib_deps = 
    jgromes/RadioLib @ ^6.6.0
    mikalhart/TinyGPSPlus @ ^1.0.3
    madhephaestus/ESP32Servo @ ^3.0.5
    adafruit/Adafruit NeoPixel @ ^1.12.0
    moononournation/GFX Library for Arduino @ ^1.4.6

[env:base]
extends = common
build_src_filter = 
    +<base/*>
    -<rover/*>
build_flags = 
    ${common.build_flags}
    -DBUILD_BASE=1
lib_deps = 
    jgromes/RadioLib @ ^6.6.0
    bblanchon/ArduinoJson @ ^7.0.4
    adafruit/Adafruit NeoPixel @ ^1.12.0
    moononournation/GFX Library for Arduino @ ^1.4.6
